version: '2.1'
services:
  argus-api:
    build:
      context: ./github-api
    volumes:
      - ./github-api:/home/node/app
    environment:
      - DB_URL=mongodb://mongodb:27017/perryworker
    ports:
      - "8070:8070"
    depends_on:
      - perry-worker
      - mongodb
  
  argus-dashboard:
    build:
      context: ./dashboard
    environment:
      - API_URL=http://argus-api:8070
    depends_on:
      - argus-api
    ports:
      - "8071:8071"

  mongodb:
    image: mongo
    container_name: "mongodb"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017 --quiet
      interval: 5s
      retries: 3

  perry-worker:
    build:
      context: ./perryworker
    environment: 
      - GITHUB_API_TOKEN=
      - MONGO_URL=mongodb://mongodb:27017/perryworker
      - MONGO_USER=
      - MONGO_PASSWORD=
    depends_on:
      mongodb:
        condition: service_healthy
